### ISSUE TITLE
tweepy.errors.Forbidden: 403 Forbidden

### ISSUE THREAD

**Issue by Cpk0521** [nan0521/Cue-Tweet-Bot#1]
![image](https://github.com/nan0521/Cue-Tweet-Bot/assets/10280294/1389e3c1-efcc-49e2-bbeb-899eb9927478)

**Comment by Cpk0521** [comment]
![image](https://github.com/nan0521/Cue-Tweet-Bot/assets/10280294/736aa4ad-d8c4-4974-9b88-3ef7c599fdff)

**Comment by nan0521** [comment]
[dfd0847](https://github.com/nan0521/Cue-Tweet-Bot/commit/dfd08475f4b806c509374a5df0162765ef77defa)
